### ISSUE TITLE
ISSUE: Better handling of concurrent Domain request handling

### ISSUE THREAD

**Issue by f-trivino** [freeipa/ipa-tuura#25]
if 2 calls are done to add the same domain, the REST API does not complain but we end up with 2 domains in the sql db and only one in sssd.conf. Removing any of these domains results in an inconsistency (one remaining domain in sql, but no domain in sssd.conf).

**Comment by spoore1** [comment]
I believe there is also a problem with adding the same IPA Integration domain a second time.  While writing test automation, I use keycloak's export/import function to set the state of the keycloak server to a known state.  Well the import on teardown to restore state mostly seems to work if using the delete domain option from the storage plugin but, I see a traceback on the ipa-tuura server after an attempted service-add:



```
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: useradd scim: useradd: user 'scim' already existsMay 31 15:57:19 ipa-tuura.bridge.test python3[306]: raw: service_add('ipatuura/ipa-tuura.bridge.test@IPA.TEST', version='2.251')
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: service_add('ipatuura/ipa-tuura.bridge.test@IPA.TEST', version='2.251')
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: [try 1]: Forwarding 'service_add/1' to json server 'https://master.ipa.test/ipa/json'
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: HTTP connection keep-alive (master.ipa.test)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: HTTP connection destroyed (master.ipa.test)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: Traceback (most recent call last):
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 709, in single_request
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.__send_request(h, host, handler, request_body, verbose)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 766, in __send_request
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.send_content(connection, request_body)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 523, in send_content
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     connection.endheaders(request_body)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/http/client.py", line 1278, in endheaders
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self._send_output(message_body, encode_chunked=encode_chunked)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/http/client.py", line 1077, in _send_output
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.send(chunk)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/http/client.py", line 999, in send
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.sock.sendall(data)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/ssl.py", line 1241, in sendall
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     v = self.send(byte_view[count:])
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/ssl.py", line 1210, in send
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self._sslobj.write(data)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2423)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: Internal Server Error: /domains/v1/domain/
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: Traceback (most recent call last):
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 1146, in forward
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self._call_command(command, params)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 1122, in _call_command
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return command(*params)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 1276, in _call
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self.__request(name, args)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 1239, in __request
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     response = self.__transport.request(
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:                ^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/xmlrpc/client.py", line 1166, in request
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self.single_request(host, handler, request_body, verbose)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 709, in single_request
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.__send_request(h, host, handler, request_body, verbose)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 766, in __send_request
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.send_content(connection, request_body)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 523, in send_content
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     connection.endheaders(request_body)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/http/client.py", line 1278, in endheaders
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self._send_output(message_body, encode_chunked=encode_chunked)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/http/client.py", line 1077, in _send_output
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.send(chunk)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/http/client.py", line 999, in send
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.sock.sendall(data)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/ssl.py", line 1241, in sendall
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     v = self.send(byte_view[count:])
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib64/python3.11/ssl.py", line 1210, in send
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self._sslobj.write(data)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2423)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: During handling of the above exception, another exception occurred:
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: Traceback (most recent call last):
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     response = get_response(request)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:                ^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return view_func(*args, **kwargs)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self.dispatch(request, *args, **kwargs)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     response = self.handle_exception(exc)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     self.raise_uncaught_exception(exc)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     raise exc
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     response = handler(request, *args, **kwargs)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/ipa-tuura/domains/views.py", line 41, in create
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     raise e
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/ipa-tuura/domains/views.py", line 39, in create
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     add_domain(serializer.validated_data)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/ipa-tuura/domains/utils.py", line 383, in add_domain
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     deploy_ipa_service(domain)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/ipa-tuura/domains/utils.py", line 217, in deploy_ipa_service
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     result = api.Command["service_add"](krbcanonicalname=ipatuura_principal)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/frontend.py", line 471, in __call__
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self.__do_call(*args, **options)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/frontend.py", line 499, in __do_call
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     ret = self.run(*args, **options)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/frontend.py", line 817, in run
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self.forward(*args, **options)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/frontend.py", line 839, in forward
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     return self.Backend.rpcclient.forward(self.forwarded_name,
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:   File "/usr/lib/python3.11/site-packages/ipalib/rpc.py", line 1187, in forward
May 31 15:57:19 ipa-tuura.bridge.test python3[306]:     raise NetworkError(uri=server, error=str(e))
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: ipalib.errors.NetworkError: cannot connect to 'https://master.ipa.test/ipa/json': EOF occurred in violation of protocol (_ssl.c:2423)
May 31 15:57:19 ipa-tuura.bridge.test python3[306]: "POST /domains/v1/domain/ HTTP/1.1" 500 192288
```

**Comment by spoore1** [comment]
@f-trivino 

This is the full journal log from ipa-tuura if needed:

[ipa-tuura.log](https://github.com/freeipa/ipa-tuura/files/11666022/ipa-tuura.log)
